### ISSUE TITLE
build new search form

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines#1]
On landing page, replace 'View our collection of Documents' blue section with a search form modeled after the following:

![search](https://cloud.githubusercontent.com/assets/4389360/6471586/3f42a5d0-c1ba-11e4-8479-101132b69bf5.png)

Title: 'Search Documents in CongoMines Document Library'

Below, add a small button for 'View all Documents in Library' that links to _congo-mines/library_

Document Theme, Doc Type, and Source Type should be toggle-able (allowing users to search for, e.g. all environmental documents relating to company XXX).  Feel free to style this however you see fit (rounded buttons don't fit with the rest of the site's square buttons, for example.  You've already shared some good ideas on how to design horizontal navs whose button count get pretty long.

Also, because this includes the company search functionality, we can remove the 'Mining Company Search' form at the bottom of the page.

**Comment by jameslaneconkling** [comment]
Noting this here:

they also suggest having a basic search form (one empty field and search button), and an advanced search (like what's pictured above).  Advanced search could be hidden until users click an 'advanced search' button below the basic search.

Note sure if it makes sense to try and build this now, or wait until we have a more clear decision on this.

**Comment by zuuring** [comment]
Sounds good to me! What I'll do is iterate these ideas with some of mine into a new search field design with advanced options. Will keep you posted

**Comment by jameslaneconkling** [comment]
Sounds great.  Carter Center has finally (almost) formalized the categorization schema of each document.  I've updated the [Joint Notes](https://docs.google.com/document/d/12F67crzhXZQqhgzWevQLXpy6nF6eOsi-ymALGCE2ClA/edit) doc under **Proposed categorization of Document Library**.

In short:
- themes can be broken into _category groups_ and categories; doc type and source type are only subset into categories.
- some of the specifics might change slightly, but I'm pretty sure this is a pretty good indicator of the approx. size of each list.  I particularly liked the below screenshot which you shared earlier.  Might be useful to organize theme search in particular.

![screenshot at feb 26 10-56-58](https://cloud.githubusercontent.com/assets/4389360/6513815/b69d55de-c34b-11e4-8133-9c8fddd086ae.png)

**Comment by jameslaneconkling** [comment]
@Stadl0r noticed some strange behavior with the checkbox buttons: can't always click them off once they are on.  Look into it?

**Comment by jameslaneconkling** [comment]
@Stadl0r alright, checkboxes work nicely.

Can we 'tighten' the layout some?  I.e. shrink vertical spacing and maybe decrease font size.  I'm viewing this on a smaller screen (i.e the screens I've seen most people use in the DRC) and viewing the complete 'advanced search' form involves a lot of scrolling.

For that matter, does Foundation expose a way to easily manipulate the base vertical spacing?  I feel like much of the site could benefit by shrinking some of the vertical spacing to aid viewing on smaller screens (by smaller, I don't mean mobile or tablet, just small laptops).
