### ISSUE TITLE
Twitter Feed

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines#2]
@Stadl0r how easy is it to build a twitter feed widget (doesn't twitter have easy embed tools for this)?

I don't usually love twitter feeds, but they asked for one.  Any thoughts on where this could go?

**Comment by zuuring** [comment]
@jameslaneconkling perhaps we could do a nice minimal embed timelne into the footer? That might look the nicest in my opinion!

**Comment by jameslaneconkling** [comment]
Sounds great.  Yeah, I imagine that's the best place to put it: out of the
way, but not so out of the way folks can't find it.

**Comment by timwaters** [comment]
Looks a bit odd for me

![image](https://cloud.githubusercontent.com/assets/48941/6599965/88ef57b4-c804-11e4-910c-6ffdab8a3dde.png)

**Comment by jameslaneconkling** [comment]
OK, looks like it's an issue with 'medium' screen widths (< 1020px wide), when foundation does some responsive re-juggling of content.

Looks like a quickfix is just to set the footer height to auto for medium/small screens (rather than set it explicityly to 450px), but maybe there's a better way in line with foundation's philosophy.

Also,  the other footer content alignment looks off on medium and small screens.

**Comment by zuuring** [comment]
Will work on that but  templates haven't been mobile optimized yet until templates are approved. But I can fix that up if you want as well!
