### ISSUE TITLE
Add Social Media Share buttons to Document page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines#20]
- post link to facebook
- tweet link

**Comment by zuuring** [comment]
I've updated with social buttons, but is there an effective way within jekyll to pull current page url for FB share button?

**Comment by jameslaneconkling** [comment]
{{site.baseurl}}{{page.url}} should do the trick.  But if you keep running
into issues hooking it up, just leave it blank.  Everything will need to be
translated into a rails environment anyway.
