### ISSUE TITLE
Create style guide page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines#4]
Can you create a new page to act as the style guide?

I've done this on other pages, e.g. my [portfolio site](http://jameslaneconkling.github.io/style-guide/).  Foundation does this automatically for out-of-the-box foundation sites.

Essentially, it's a page that demonstrates the style conventions of the site: both how to implement them, if you are looking at the html, and how they render, if you are looking at the page in the browser.  It shouldn't require any additional design, and shouldn't be linked to from anywhere w/i the site; it's just meant to demonstrate how the css framework is implemented.

Makes it a lot easier to hand off the design to another designer who doesn't know your conventions, and also makes it easier to iterate on designs independent of content.

Probably will just require copy/pasting components from the site into a new page at `/style-guide/index.html`, such as:
- headings, banners, and other block tags
- links, buttons, and other inline content
- basic forms
- tables
- grids

**Comment by zuuring** [comment]
Let me know how this is!

http://crowdcover.github.io/congo-mines/style-guide/

**Comment by jameslaneconkling** [comment]
looks good.  thanks.
